all: IrvingAlgorithmTest

IrvingAlgorithm:
	g++ -std=c++17 -c IrvingAlgorithm.cpp

IrvingAlgorithmTest: IrvingAlgorithm
	g++ -std=c++17 IrvingAlgorithm.o IrvingAlgorithmTest.cpp -o IrvingAlgorithmTest
